### ISSUE TITLE
vc14 fails with 1638 exitcode

### ISSUE THREAD

**Issue by pavel-shvagirev** [sous-chefs/vcruntime#36]
vc14.rb fails with:
```
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0, 3010], but received '1638'
``` 
1638 means that another version of that package is already installed [(see error codes description here)](https://johnkoerner.com/install/windows-installer-error-codes/).
In my case 14.28.29334.00 is already installed while latest cookbook release has attribute value of 14.28.29325.2.

Therefore there are several ways:
- no change but need to bump the version up: we keep failing cookbook runs in order to force ourselves/users to update VC version
- add 1638 to `returns [0, 3010]`
- add `not_if` by values in `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\` (not an easiest way though)

**Comment by pavel-shvagirev** [comment]
BTW, obviously not just vc14.rb is supposed to result with that errorcode but barely every other installer too

**Comment by Xorima** [comment]
let's allow 1638 for now, if you can do the pr we can get this shipped

**Comment by ramereth** [comment]
My vote would be to go ahead and bump the version and also add `1638` to returns `[0, 3010]` so that it will at least run if a newer version is released or installed.

@Xorima @tas50 thoughts?

**Comment by pavel-shvagirev** [comment]
Investigation shows that v14.28.29334 that I have has quite strange background: it is not published on VCredist main MS website and likely was installed via Windows Update. Furthermore there seems to be no easily accessible downloads of that version. And finally, the latest officially available version for VC2019 download is exactly what @ramereth had already mentioned in cookbook's attribute.

The 14.28.29334 version was likely intended by MS to be a kind of a cumulative bundle of 2015.

As a result I don't thing there is a need to change any version for now. At least since there is no corresponding downloads available.

Will add 1638 to acceptable returns instead.

**Comment by pavel-shvagirev** [comment]
Can't help mentioning that `returns`-solution has one significant disadvantage. Since installation is triggered _every chef-client run_, it constantly tries to update a resource rather than skip it with "action create (up to date)". Probably binaries download is triggered every run too.

Its really worth updating the version.
