### ISSUE TITLE
Install switches update for VC version >= 2012

### ISSUE THREAD

**Issue by pavel-shvagirev** [sous-chefs/vcruntime#37]
I'd use `/install /quiet /norestart` install switches for VC versions 2012 and newer. Currently used `/q` seems to be working fine but according to different docs and articles available ([example](https://silentinstallhq.com/visual-c-redistributable-silent-install-master-list/)) `/q` was used for earlier versions.

Another reason is that `/norestart` switch should avoid an unexpected reboot triggeted by corresponding Group Policies.

**Comment by ramereth** [comment]
Feel free to make a PR which addresses this.
