### ISSUE TITLE
vc6 bad checksums

### ISSUE THREAD

**Issue by whitemars** [sous-chefs/vcruntime#42]
## Brief Description

The checksums in the attribute for the `Microsoft Visual C++ 2005 Redistributable`'s do not match the checksums downloaded from Microsoft. This will cause the recipe to fail as that is checked by the `windows_package` resource. They just need to be updated.

## :waffle: Cookbook version

We are using `1.2.1` but the checksums have not changed in the cookbook in the newer versions.

## Steps To Reproduce

Run the vc6.rb recipe

## Helpful resource

https://www.microsoft.com/en-us/download/details.aspx?id=26347

**Comment by ramereth** [comment]
@whitemars please feel free to create a PR which addresses this!
