### ISSUE TITLE
Recipe fails unless using newest cookbook version AND newest package

### ISSUE THREAD

**Issue by ryan-strauss** [sous-chefs/vcruntime#45]
## :ghost: Brief Description

Specifying an older version does not work.

## :pancakes: Cookbook version

2.2.2 & 2.2.3

## :woman_cook:  Chef-Infra Version

16.2.73

## :tophat: Platform details

Azure Windows 2019
platform_version=10.0.17763

## Steps To Reproduce

Berksfile: 
cookbook 'vcruntime', '= 2.2.3'

recipe:
node.override['vcruntime']['vc14']['version'] = '14.28.29914.0'
include_recipe 'vcruntime::vc14'

```
NoMethodError
-------------
undefined method `[]' for nil:NilClass

Cookbook Trace: (most recent call first)
----------------------------------------
17:  # See the License for the specific language governing permissions and
 18:  # limitations under the License.
 19:  #
 20:
 21:  if platform?('windows')
 22:    case node['kernel']['machine']
 23:    when 'x86_64'
 24>>     windows_package node['vcruntime']['vc14']['x64'][node['vcruntime']['vc14']['version']]['name'] do
 25:        checksum node['vcruntime']['vc14']['x64'][node['vcruntime']['vc14']['version']]['sha256sum']
 26:        source node['vcruntime']['vc14']['x64'][node['vcruntime']['vc14']['version']]['url']
 27:        installer_type :custom
 28:        returns [0, 1638, 3010]
 29:        remote_file_attributes({
 30:          path: "#{Chef::Config[:file_cache_path]}\\package\\#{node['vcruntime']['vc14']['x64'][node['vcruntime']['vc14']['version']]['name']}.exe",
 31:          checksum: node['vcruntime']['vc14']['x64'][node['vcruntime']['vc14']['version']]['sha256sum'],
 32:        })
 33:        options '/install /quiet /norestart'
```
 The above attribute does not exist with the version I specify. `[node['vcruntime']['vc14']['version']]` only has the newest.

I also pinned earlier version (2.2.2) and the checksums do not match, because the source URL only downloads the newest version. 

## :police_car: Expected behavior

2.2.3: It should install 14.28.29914.0 when I specify the version.
2.2.2: When I use the the default attribute with 14.28.29914.0, it still downloads the new version and checksums fail.

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by derekgroh** [comment]
This is a limitation of how Microsoft is releasing the 2015-2019 version now. They no longer provide a static link for each version and instead publish a single link which gets updated with the latest version.

In order to use a prior version of 2015-2019 you would also have to have that version downloaded locally and replace `node['vcruntime']['vc14']['url'] as well.

**Comment by derekgroh** [comment]
Tech Powerup is hosting a repository of older versions, but they are within a ZIP file, if you want to use a prior version.

https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

**Comment by JHBoricua** [comment]
> This is a limitation of how Microsoft is releasing the 2015-2019 version now. They no longer provide a static link for each version and instead publish a single link which gets updated with the latest version.
> 
> In order to use a prior version of 2015-2019 you would also have to have that version downloaded locally and replace `node['vcruntime']['vc14']['url']` as well.

This could be clarified better in the README.md file for the vc14 runtime to avoid confusion. It looks like for the newly released 2022 runtime (2015-2022) Microsoft will be using the same approach. I'm terrible at writing documentation though or I'd do it myself.
