### ISSUE TITLE
vcruntime::vc14 multiple run deletes dll files

### ISSUE THREAD

**Issue by whyte624** [sous-chefs/vcruntime#47]
## :ghost: Brief Description

After first run of the recipe package is installed.

Second run deletes dll files.

I tried from console to do this:

```
c:\chef\cache\package>"Microsoft Visual C++ 2019 Redistributable (x64) - 14.29.30037.exe" /install /quiet /norestart

c:\chef\cache\package>"Microsoft Visual C++ 2019 Redistributable (x64) - 14.29.30037.exe" /install /quiet /norestart
```

First run: dlls installed. Second run: dlls deleted.

Same thing happens when I run recipe twice. 

Btw, third and next runs will not restore dlls (VCRUNTIME140.dll and MSVCP140.dll)

## :pancakes: Cookbook version

2.2.4

## :woman_cook:  Chef-Infra Version

17.1.35

## :tophat: Platform details

Windows Server 2016/2019

## Steps To Reproduce
Run recipe twice

## :police_car: Expected behavior

Installed and working package (all dlls present)

**Comment by EddieRockwell** [comment]
Experiencing this same behavior

**Comment by EddieRockwell** [comment]
Ok. After reviewing. We've fixed our instance by ensuring that the version and name are the correct / same as the uninstall registry entry. 
In your code the name should be 
(for x86):
`"name" : "Microsoft Visual C++ 2019 X86 Additional Runtime - 14.29.30037"`
the version should be:
`"version" : "14.29.30037"`
(for x64):
`"version" : "14.29.30037"`
`"name" : "Microsoft Visual C++ 2019 X64 Additional Runtime - 14.29.30037"`

If you already have a broken version installed, it may not uninstall and reinstall via chef as the uninstall registry key may remain. so manually remove and update chef and re-run.

**Comment by ramereth** [comment]
Is there a fix we need to do in the cookbook? If so can you please make a PR to address it?
